steps:
  # Step 1: Change directory to `src/docker/`
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$SHORT_SHA', '.']
    dir: 'src/docker'  # Run the build command inside the correct directory

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$SHORT_SHA']

# Specify the output image location
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$SHORT_SHA'

# Enable logging to Cloud Logging (instead of a GCS bucket)
options:
  logging: CLOUD_LOGGING_ONLY
